### ISSUE TITLE
Water Electrolysis

### ISSUE THREAD

**Issue by Sleeeper** [jinxOAO/DSPmods_BepInEx#1]
I suggest to not change hydrogen fuel values, to make it fit better with other mods, but instead balance around water>hydrogen recipe ratio and time of processing.

So instead of reducing fuel value by ~18 times (from 8Mj to 440kJ)
it could be 18 water to 1 hydrogen in 9 seconds. (instead of 1 to 1 in 0.5 seconds)
(or shorter period, for less energy consumption)

**Comment by jinxOAO** [comment]
Thank you for your suggestion, I have modified the mod so that players can turn off the all the balance modification. However, the rate of hydrogen generation cannot be reduced. Due to the low power of chemical plants, if I want that the electrolysis of water cannot be used to generate power, the rate of hydrogen production must be reduced to about 0.05 per second, which will cause the efficiency of chemical plants to be much lower than that of orbital collectors and crude oil refining It loses the meaning of this mod.

**Comment by jinxOAO** [comment]
> I suggest to not change hydrogen fuel values, to make it fit better with other mods, but instead balance around water>hydrogen recipe ratio and time of processing.
> 
> So instead of reducing fuel value by ~18 times (from 8Mj to 440kJ)
> it could be 18 water to 1 hydrogen in 9 seconds. (instead of 1 to 1 in 0.5 seconds)
> (or shorter period, for less energy consumption)

I have made changes and you can now turn off the balance adjustment. 
But I did not reduce the hydrogen production rate. Since I want to provide a low-cost and fast hydrogen production method in the early stage.
