### ISSUE TITLE
[Suggest] - SmartTank new building/recipe

### ISSUE THREAD

**Issue by Crazyht** [jinxOAO/DSPmods_BepInEx#15]
Hi, 

In place of override of all tank, you can create a new recipe for smart tank, so no config for type we want overflow and play with input switch to decide if tank accept overflow or not. 

And has nice to have change design (color for exemple) of placed smart tank compare to vanila tank.

Thx

**Comment by jinxOAO** [comment]
This is a good idea, but since I am a little busy lately, this change will not be uploaded soon. I will try to do this when I have time. I really want to have the change color design for the model, but that is beyond my ability. The only thing that I can do now is changing the icons. Anyway, great thanks for your suggestion!
