### ISSUE TITLE
Recycle Fuel Rods

### ISSUE THREAD

**Issue by Lt-Sparky** [jinxOAO/DSPmods_BepInEx#33]
Haven't played in a while and through trial and error this mod causes the following to happen when I open the game and locks it there..
![recyclefuelrods](https://user-images.githubusercontent.com/85095233/151289511-14813b60-d2aa-41ed-adfb-5066f323c551.jpg)
.

**Comment by jinxOAO** [comment]
First of all, it seems that this error was caused by the changing of the return value type of the "InsertInto" function. I have tried to fix this problem a few days ago(and succeeded), but the reason why the mod has not been updated is that, even after fixing this apparent error, the "recycle fuel rods" mod still doesn't work(mainly because the inserter can't grab the empty fuel rods), and I still can't fix various issues(mainly game crushes, almost certain to happen within minutes) after a whole day's work. Sorry I can't update this mod at the moment. Thank you for your feedback, I will continue to try it if I have time, and anyone is welcome to help me modify the source code. If necessary, I can provide my original modification ideas.

**Comment by brewskidafixer** [comment]
hope you are able to update soon, I really like this mod. while you are working on a fix as a temp fix please add a recipe that 
10 Deuterium -> 1 Deuteron fuel rod 
6 Antimatter + 6 Hydrogen -> 1 Antimatter fuel rod

**Comment by jinxOAO** [comment]
Hope this temp fix can work properly. Please ignore that some redundant and non-interactive recipes or items still exist.
DOWNLOAD .dll here.
https://github.com/jinxOAO/DSPmods_BepInEx/releases/tag/0.1

**Comment by db48x** [comment]
That fixes the errors. I should load up my other save where I was actually recycling fuel rods and double check that it works.

**Comment by db48x** [comment]
Hmm. Well, reperfusion works, but I can confirm that my reactors weren’t actually putting out any empty fuel rods. I tried rebuilding one, but that didn’t fix it either.

I saw no crashes though, not in an hour of playing the early game nor ten minutes with lots of fusion reactors humming away.

**Comment by jinxOAO** [comment]
Hey! Good news. I've restored the function and made it adapt to the latest version of the game. No more bugs, for now. You can go to
https://dsp.thunderstore.io/package/jinxOAO/RecycleableFuelRods/
to download the latest version. Don't forget to DELETE THE TEMP FIX (RFRTempPatch.dll) after you download the new version!!!!!! @db48x @brewskidafixer 
Please contact me if there is any problems or bugs. Thx.

**Comment by db48x** [comment]
Thank you! it now works perfectly again.
