### ISSUE TITLE
SmelterMiner Exception on empty vein

### ISSUE THREAD

**Issue by AandD** [jinxOAO/DSPmods_BepInEx#39]
![PtFPrFYa](https://user-images.githubusercontent.com/35153/152864762-b0b4740e-86e9-4e9c-9750-3fd15631d709.jpg)
Error started popup then i loaded game.
Second problem is that if the output faster then mining speed then it starts to output vanila product: ore or stone etc. So you have to limit ouput with belts mk1 and spliters to keep full mining buffer.

**Comment by jinxOAO** [comment]
I'll try to fix that. will you please try the version 1.4.1 and see if the error still remains? That may help me to locate the problem. And it will be greatly helpful if you can share your game save.

**Comment by jinxOAO** [comment]
for the second problem, sorry i do not quite understand. Do you mean that when the belt is fast and the maining speed is low, it will output vanilla product? and, Does this problem only happen on Advanced smelterminer or both small and big smelterminer?

**Comment by AandD** [comment]
Yes, you right. Only small.

**Comment by jinxOAO** [comment]
I thought the same multithreading thing, but unfortunately I can't use your save. When I've used all the mods you have installed, I can't get to the game menu. When I use my plugins, (including DSPModSave and compresssave), I can't load your save, I get an GameAchievementData.Import error when I load it.

Since I can't reproduce the two problem you mentioned in anyone of my save. If these two bugs are very easy to reproduce in your games ( I mean: almost every time a vein is depleted, the problem will occur.  And every time the high-speed conveyor belt is used, it will result in the output of mixed product.)  It is most likely caused by a mod conflict. If so, you can try uninstalling the DSPOptimizations Mod and see if the problem is resolved. Because I only know that this mod provides multi-threaded optimization related features. Also, make sure your game is updated to the latest i.e. 0.9.24.11286.

**Comment by jinxOAO** [comment]
I'll keep looking for the cause, but I'm not sure how long it will take. Besides, you can try use the features that I provided in the smelterminer mod to stop the consumption of ore veins by ActiveCustomizeMiningRate and set the MiningRate to 0.  This should temporarily fix the depleted vein error, as no more veins will be depleted.

**Comment by AandD** [comment]
Well, i lost all clues. I even started new game with disabled all mods switching on one after another(except disabled miner notifer which is waiting when author fix error) to find conflicted one but there all works perfect and there are no anoying vanila products from small miners. I can only gues that problem may ocure at later game stages when fps drops may ocure. So i gues this can be closed. Sory for your time.
