### ISSUE TITLE
[Compatibility] MoreProtoPages has a conflict with CommonAPI's TabSystem

### ISSUE THREAD

**Issue by kremnev8** [jinxOAO/DSPmods_BepInEx#43]
It seems your new mod [MoreProtoPages ](https://dsp.thunderstore.io/package/jinxOAO/MoreProtoPages/) is adding 6 new tabs. This is causing a conflict with a feature of CommonAPI that also adds tabs on request. 
I ask you to either rewrite your mod to utilize CommonAPI's TabSystem or rewrite all of your mods using it and deprecate it. 

I believe such feature should be placed in a common library. Currently I'm trying to make CommonAPI a such library. I would be glad if you would be willing to cooperate. If you believe that my TabSystem doesn't have certain feature I'm willing to improve it.

You can find source code for this feature [here](https://github.com/kremnev8/CommonAPI/blob/master/CommonAPI/Systems/TabSystem/TabSystem.cs). I don't have very deep documentation for it, as so far no mods use it, other than my WIP mod `SignalNetworks`. Here is short usage:
```cs
int tabId = TabSystem.RegisterTab($"{MODID}:{MODID}Tab", new TabData
(
    "SignalNetworksTabName",
    "Assets/SignalNetworks/Icons/signal-networks"
));
```

Here you can see the issue. With MoreProtoPages:
![изображение](https://user-images.githubusercontent.com/12484618/154034915-cb4e69df-2b2a-496d-aa1b-2ac80c251ac4.png)
Without it:
![изображение](https://user-images.githubusercontent.com/12484618/154036586-131f4134-d773-4478-bed0-d151dd9aaf5a.png)

**Comment by jinxOAO** [comment]
Of course, Love your mods and I'd love to cooperate. Sorry I didn't realize this feature is already provided by commonAPI, and sorry to trouble you. Seems the best way is to deprecate the MoreProtoPages and change my other mods. And I might need some time to do that. But I have some questions.
1. I don't understand {MODID}, how should I fill in the first parameter of TabSystem.RegisterTab and the iconPath of the new TabData? This issue prevents me from modifying my mod as I don't currently know how to use it. I'm very amateur as a mod developer, sorry about that. Hope you can help me understand how to fill in the parameters. 

For example I've loaded the icons in the past like this
```cs
var ab = AssetBundle.LoadFromStream(Assembly.GetExecutingAssembly().GetManifestResourceStream("MoreProtoPages.addtypeicon"));
Sprite AddPageIcon = ab.LoadAsset<Sprite>("add1");
```

2. If two mods want to share one new tab, can they try to register the same tab to minimize waste. It would be great if it could. Otherwise they must have one as a dependency, and the other will not register new tabs but use them directly. I think the latter is not so good.

**Comment by JamieRCHI** [comment]
Could this be why MoreProtoPages is not compatible with DSPMultiplyStackSize mod?
The tabs are overlapping the buttons added by the DSPMultiplyStackSize mod.

**Comment by jinxOAO** [comment]
> Could this be why MoreProtoPages is not compatible with DSPMultiplyStackSize mod? The tabs are overlapping the buttons added by the DSPMultiplyStackSize mod.

Seems right. Can't edit the stack size if MoreProtoPages is installed.

**Comment by kremnev8** [comment]
1. First parameter to this function is a UNIQUE string ID of the tab. I have it to be `$"{MODID}:{MODID}Tab"`, which resolves to `SignalNetworks:SignalNetworksTab`. It can by any unique string. `MODID` is just your mod id (name) as a string const. Here I use just my mod name, but I recommend using your full GUID. You can define that like so
```cs
public const string MODID= "SignalNetworks";
```
2. Regarding loading assets. I don't use this approach. Instead I prefer to load asset bundles created in Unity Editor. I have information on [setting unity up](https://github.com/kremnev8/DSP-Mods/wiki/Setting-up-development-environment). But for the purpose of creating bundle with images, you can use a simple Unity project with correctly set up paths. You can read about that [here](https://github.com/kremnev8/CommonAPI/tree/master/CommonAPI/Systems/ProtoRegistrySystem#troubleshooting)
3. Two mods can use one tab. To do that they need to use common tab ID. In that case you can use a ID common for all your mods. For example `GniMaerd.DSP.plugins:JinxOAOTab`. Each mod will call `RegisterTab(string ID, TabData tab)` with same ID, and the first one to do so will make a tab, second and after will revive tab number.

**Comment by jinxOAO** [comment]
Thanks, I'll try that soon.

**Comment by jinxOAO** [comment]
I'm sorry I still can't load the icon and it keeps poping up errors.
I'd like to deprecate MoreProtoPages directly, but because some other players have used the mod, and I haven't learned how to use the common API correctly to add new tabs yet. Therefore, I rolled back MoreProtoPages to the earliest version, which means that there are no additional tab icons, and all page can be switched by number keys. And I will add the commonAPI as its dependency, since that is the better way. Will that be ok? Now this mod should no longer interfere with the additional tabs or buttons created by the commonAPI. On the other hand, if the index of the new tab provided by the commonAPI is 3-9, the keys provided by moreprotopages can also match their buttons.

**Comment by kremnev8** [comment]
If you would show what you are doing, I will be able to help. Also if you have Discord, I can help you there. As for keybinds, they can be added to CommonAPI.

**Comment by jinxOAO** [comment]
That will be great. I was using
```cs
void Awake()
        {
            using (ProtoRegistry.StartModLoad(GUID))
            {

                //Initilize new instance of ResourceData class.
                string pluginfolder = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
                resources = new ResourceData(GUID, "GMMoreProtoPages", pluginfolder); // Make sure that the keyword you are using is not used by other mod authors.
                resources.LoadAssetBundle("addtypeicon"); // Load asset bundle located near your assembly
                //resources.ResolveVertaFolder(); // Call this to resolver verta folder. You don't need to call this if you are not using .verta files 
                ProtoRegistry.AddResource(resources); // Add your ResourceData to global list of resources
            }

            TabSystem.RegisterTab($"{MODID}:{MODID}Tab", new TabData("mppnamegm", "assets/GMMoreProtoPages/add1"));

            
            

        }
```
and the assetbundle was like that in unity
![image](https://user-images.githubusercontent.com/49783661/154064558-09adb96c-d413-414d-a4c0-c9f4f9988b87.png)

and the error
![image](https://user-images.githubusercontent.com/49783661/154064922-f549a1d5-a396-4f2c-ad26-4e1ee2d23dd2.png)

**Comment by kremnev8** [comment]
Please show your plugins folder, especially folder with CommonAPI and your plugin. Also make sure you don't copy CommonAPI with your plugin dll.

**Comment by kremnev8** [comment]
Your code and unity project looks almost right.
1. Please move `TabSystem.RegisterTab` call inside the `using` statement.
2. In code you have `assets/GMMoreProtoPages/add1` as your path to icon. But in unity you can see `assets/MoreProtoPages/add1`

**Comment by jinxOAO** [comment]
Sorry my bad, forget to set copy to false.
now it's
![image](https://user-images.githubusercontent.com/49783661/154065987-0a79a16e-1472-4412-84c2-e1f20a0cc11e.png)

![image](https://user-images.githubusercontent.com/49783661/154066340-9458c556-e5fa-4388-a806-60bffef55c79.png)

**Comment by kremnev8** [comment]
You need a `[CommonAPISubmoduleDependency(nameof(ProtoRegistry))]` attribute on your plugin class. Like [this](https://github.com/kremnev8/CommonAPI#usage-example). Also this is a recommendation and not required, but please move each mod to it's own folder.

**Comment by kremnev8** [comment]
Well as error suggests you need to add `, nameof(TabSystem)` to your statement.

**Comment by jinxOAO** [comment]
Thanks, That worked! I'll start to change my other mods now. 
Are you kind of an administrator of dsp.thunderstor.io? Can you please delete the MoreProtoPages after I updated my other related mod? Since I don't know how to do that...... Or what should I do about the MoreProtoPages if I want to deprecate it?

**Comment by kremnev8** [comment]
No. I'm not. You will need to ask Mythic on modding discord to do that.

**Comment by jinxOAO** [comment]
Sure! I don't have a discord account. Hope you can help me for that. Thanks a lot!

**Comment by jinxOAO** [comment]
Thanks again. Your mods are useful and I've learnt a lot from you.

**Comment by kremnev8** [comment]
Also note that you need to register string with ID `mppnamegm` for tab text to be proper.

**Comment by jinxOAO** [comment]
got it!

**Comment by kremnev8** [comment]
While this is not exactly related I do need to note that you did not correctly register the tabs to be the same one.
![изображение](https://user-images.githubusercontent.com/12484618/154089517-6d2dd722-b63b-453a-9335-82a0329ca595.png)
You have two now.

**Comment by kremnev8** [comment]
And on another unrelated note. In your mods you clearly don't use full potential of CommonAPI's ProtoRegistry. When making your next mod related to new items and stuff, would you be willing to try it out?

**Comment by jinxOAO** [comment]
thanks for reminding. Yes this is intentional. Because i got another error of loading the same assetbundle occurred when I tried to register the same tab, and  since the two did not belong to the same category, I just decide to register them separately. 
I'm happy to try it. Indeed I don't use full potential of CommonAPI's ProtoRegistry, because I first learned how to use LDBTool (And it had a video tutorial, plus, with my own language, so.). But I would love to try more about CommonAPI next time.

I do have a little suggestion. I suppose you've already noticed that the new tab icon is a little bit lower than the vanilla icons. So if you can adjusting the position of the button icon a little bit, that will be perfect. And the font size of Chinese tab name seems a little larger. But it was not a big problem. Thanks again.
![image](https://user-images.githubusercontent.com/49783661/154092064-0abbeaf2-168e-4873-a6f4-a42030145c5a.png)

**Comment by kremnev8** [comment]
Did you try to just rename the bundle? Also what you can do is try to get the asset bundle index using this method: <https://github.com/kremnev8/CommonAPI/blob/c80bd35b925c07db60e913aef231da566621658c/CommonAPI/Systems/TabSystem/TabSystem.cs#L53> if you get a `ArgumentException` register it, otherwise use it.

**Comment by jinxOAO** [comment]
Yes, i've tried. Maybe I'll try to repack another bundle next time. Thank you for your patience. Just did not figure out how to use GetTabId(string tabId) since it is not static and I dont know where I can find an instance of TabSystem. Sorry if I'm being stupid, I didn't study C# systematically :(

**Comment by kremnev8** [comment]
> I dont know where I can find an instance of TabSystem. Sorry if I'm being stupid, I didn't study C# systematically :(

You can't. That's a bug.

**Comment by kremnev8** [comment]
Another idea I have about loading two of the same bundle is to put a try catch to exception you get around it. Since the bundle is one, which ever first loads is going to provide the asset.

**Comment by jinxOAO** [comment]
Seems practicable. Will try that next time when I need to share tabs, thx.

**Comment by kremnev8** [comment]
I suggest you do that now. Your 2 tab is nearly empty.

**Comment by jinxOAO** [comment]
That worked.
