### ISSUE TITLE
Balance of more megastructures

### ISSUE THREAD

**Issue by Valoneu** [jinxOAO/DSPmods_BepInEx#46]
You might reconsider the balance side of the mod cause i got like 1mil hashes / s with almost no sphere, if you want help with that ill try them tomorrow and send here what i think would be good. Anyway very good mod and keep up the good work.

**Comment by jinxOAO** [comment]
Thanks, I'm thinking about reducing the base speed to 1/10, and whether it's appropriate to reduce the bonus effect of technology (currently +100% base speed per level, maybe it can be change to +10%/lvl ?).  You are always welcome to send your suggestions here, and that will very helpful.

**Comment by Valoneu** [comment]
ye i think 1/10 of the nexus is good and would you be able to add more of the receivers for matter decompressor, like for every ore

**Comment by jinxOAO** [comment]
The current build bar is relatively insufficient, especially I just received an issue saying that my build bar has conflicted with another mod, and I don't plan to add too many receivers, especially rare minerals, because I feel that other rare minerals are not very scarce except unipolar magnets. I am still considering the necessity of adding other receiving devices. If you can give me a few of the most necessary mineral types, I will try to add them in the next version.

**Comment by Valoneu** [comment]
Coal / spiniform / kimberlite / optical / oil / water / acid / stone  -  they are sorted by priority

**Comment by jinxOAO** [comment]
OK, I will add some new receivers in the next version according to the priority and my consideration. While, due to the current recipe conflict with another mod (which has not been published on thunderstore.io, named ProjectGenesis), I might need to make some other modifications and update them together in the next version, which should cost longer time.

**Comment by Benc85** [comment]
I've setup a small Science Nexus (currently showing as 1.4gw output) that is only producing 3000h/s. For the investment, that seems like an awfully bad return. I dunno how big that other guy made his sphere to get 1 mill /s but the nerf seems to make the thing kinda Pyrrhic.

Does the thing scale with how many research facilities you have in the system / cluster, or is it a direct conversion of power to h/s?

**Comment by jinxOAO** [comment]
> I've setup a small Science Nexus (currently showing as 1.4gw output) that is only producing 3000h/s. For the investment, that seems like an awfully bad return. I dunno how big that other guy made his sphere to get 1 mill /s but the nerf seems to make the thing kinda Pyrrhic.
> 
> Does the thing scale with how many research facilities you have in the system / cluster, or is it a direct conversion of power to h/s?

The research speed of nexus has nothing to do with the number of research facilities, but each level of research speed technology will increase the speed by 100%.
I thought the initial speed was more enticing, but the feedback made me wonder if the setting was a bit too simplistic, leading to an overdraft of the fun of the game. At the moment it looks like I may need to re-evaluate the scale. 
On the other hand, my tests of the nexus were performed on O-type stars around luminosity 2, and the largest orbit was chosen. This is also the choice I recommend to build a nexus. If you have at least level 5 research speed tech and still feel the speed is too slow, please let me know. I will recheck tomorrow and ask for more opinions about this.

**Comment by Benc85** [comment]
I have 10 research atm (1000%) and its just seems expensive for what it gives. My nexus is now at 2.7gw, offering 6000 h/s, and i could get that from 10 research labs. I figured, as it doesn't remove the need for white cubes, it doesn't really matter how fast it boosts, you're still limited by your white cube availability.

But if it's your design choice, i respect that. Just wanted to offer my opinion. If i may be so bold, I'd certainly encourage you to try to get more feedback, maybe i'm being to sensitive :)

**Comment by Valoneu** [comment]
yo benc WTF its so broken im building my nexus and researching the research speed and its getting exponencially faster and faster

**Comment by Valoneu** [comment]
sry not exponencially but its not linear but its more than linear 100% - but im already at 20MH/s

**Comment by Valoneu** [comment]
my science nexus does 945GW and i have research speed 80. IT SHOULD BE HARD TO MAKE cause its permanent and literally free science :)

**Comment by Valoneu** [comment]
btw idk if you are on discord JINXAO but im not the only one that says the nexus is busted xd

**Comment by Benc85** [comment]
That's fair enough then. My research speed is only 10, and its slow with the 1/10th nerf, but thats from my perspective. You're far more invested in research speed than i am, and JinXAO said it scales ONLY on research speed.

All im saying is perhaps instead of nerfing it for people who're so deeply invested in it, it should be re-tuned, for people who're just starting reaching the end game repeatables.

Depends entirely on whether this mod is designed with new games or existing games in mind i guess. Perhaps a tapering decrease, so its running at 10 speed at research 1, but 1 speed at research 50. I dunno.

**Comment by Benc85** [comment]
> ... its permanent and literally free science :)

The mod says its free H/S, which I assume means its only working if the labs are supplied with white cubes. Thats a REAL big difference, to be fair.

**Comment by Valoneu** [comment]
no it works always you just need to eat 1 cube so the tech updates when its done xd

**Comment by Benc85** [comment]
Ack, what? I'm burning White Cubes for no god damn reason? :(

**Comment by Valoneu** [comment]
yes i literally did 400k/m white cube and deleted all to get UPS and start rushing nexus i have only 900/m whitecubes

**Comment by Benc85** [comment]
Thanks jinxoao. Seems my reading comprehension sucks atm. All of my comments were based on my misunderstanding that the nexus was only producing h/s.

Having it boosted slightly (perhaps doubled) while your at low levels of research would certainly be welcome, but ill leave that with you. Now that i understand its "building and eating" its own cubes the slower speeds make much more sense to me.

Thanks to valoneu, for pointing that out to me. I really need to read the mod pages more carefully in future 😅

**Comment by Valoneu** [comment]
ihave 3.25TW nexus that does 533MH that shit is not balanced xd and research speed 656

**Comment by jinxOAO** [comment]
This version is unpublished. Like I said, 10 times basic speed, but only 1% speed bonus per tech level. Theoretically, compared to the previous version, the total speed will be increased before tech Lv11, and significantly reduced after that. If you have time you can try this, no rush.
https://github.com/jinxOAO/DSPmods_BepInEx/tree/mms.test.0.3.2

**Comment by Valoneu** [comment]
okay i will try when reaching the bilion so like 1 hour

**Comment by Valoneu** [comment]
like 8 minutes actually

**Comment by Valoneu** [comment]
btw may i ask why you need to still use the cube after its done?

**Comment by jinxOAO** [comment]
Because if I try to imitate the original code unlocking technology of the game, it will either cause an error or directly unlock the 10000 level technology without any actual effect. I spent an afternoon and couldn't solve it. Therefore, the code to unlock technology can only be completed by the original game, and the nexus is prohibited from completing it.

**Comment by Valoneu** [comment]
ah okay :)

**Comment by Valoneu** [comment]
so from 1G to 111MH

**Comment by jinxOAO** [comment]
This is what I expected, thanks. and congratulations for 1G.

**Comment by Valoneu** [comment]
thanks but 111MH is broken but who cares :)

**Comment by Benc85** [comment]
Dont mean to be rude, but balancing a thing around such levels of absurdity is going to give you flawed results. Definitely needs diminishing returns the further you chase it.

**Comment by Benc85** [comment]
Feedback for the v0.3.2 (from 0.3.1) my sphere jumped from 12.5k to 13.56k, but my research level is 15 atm, so that was to be expected i guess.

If i'm honest, i'd be happier if it were currently closer so 25-30k (for a 7GW sphere), and tapered off harder as i surpassed 50 research levels, but again, that's just personal preference. Do you have a baseline Sphere / research level combo you want feedback for JinxOAO?

**Comment by Valoneu** [comment]
just build less nodes and send sails sails are almost free

**Comment by Benc85** [comment]
i did something even better. i used v0.1and im upto half a million now :)

**Comment by Valoneu** [comment]
bruh

**Comment by Valoneu** [comment]
500k from 7GW (which is literally just few rockets and few sails) is insane

**Comment by Benc85** [comment]
Aww yis. Ive let the sanity ship sail, im here for the absurdity of it all now

**Comment by jinxOAO** [comment]
Thank you both for your help and patience. XD

**Comment by Benc85** [comment]
just out of idle curiosity, do you hard code each levels %, or can you input some kind of formula and it work out all the data for you?

**Comment by jinxOAO** [comment]
formula

**Comment by Speedyquader** [comment]
Currently researching level 4 research speed, and I quite like each rocket being worth 0.5 H/s at my current level - my goal tends to be 6 white cubes/sec, so I'm quickly outstripping my cube production with this Nexus lmao. I'm launching a sustained 715 rockets/min and in less than an hour, I have what seems to amount to over a blue belt's worth of science production. Haven't tried the other megas yet, but I'm looking forward to using the Warp Field Broadcast Array!

**Comment by jinxOAO** [comment]
A1: Yes, the luminosity will linearly affect nexus output.
A2: The tech boost per level has been nerfed to 1%, so it may be fairly insignificant.

**Comment by Speedyquader** [comment]
Something like that Space Factories mod would be cool, having a megastructure that would produce items based on what recipe you select, but I could see that becoming very OP very quickly, and it would probably be worse for UPS than a normal factory XD

**Comment by Valoneu** [comment]
You can use the factory stations for that
