### ISSUE TITLE
Using ReclyclableFuelRods with FusionPower eats the rods

### ISSUE THREAD

**Issue by James-Fire** [jinxOAO/DSPmods_BepInEx#65]
https://dsp.thunderstore.io/package/JamesFire/FusionPower/

It allows Deuteron Rods to be used in the artificial star, but doesn't give an empty rod back.

**Comment by jinxOAO** [comment]
Please try to find the config file "Gnimaerd.DSP.plugin.RecyclableFuelRod.cfg" and set AntiFuelRecycle to true.

**Comment by jinxOAO** [comment]
Sorry, this mod may be conflicting.

**Comment by James-Fire** [comment]
I know. I'm pretty sure something would need to be done about it on your end. Can you?

**Comment by jinxOAO** [comment]
This mod's code is like a sh*t, I'll see what I can do, I don't know.... 
btw, does the FusionPower mod create a new building or it just let the vanilla fusion reactor be able to use deuteron rods?

**Comment by James-Fire** [comment]
It allows Deuteron Rods to be used in the Artificial Star, like I said in the initial comment.

**Comment by jinxOAO** [comment]
sorry, I typed it wrong. Artificial star it is. OKOK.

**Comment by jinxOAO** [comment]
Unfortunately, bad news. I checked my code. I did not restrict the different rods to correspond to specific generators, which means that it is likely that:
The FusionPower Mod also made a Prepatch on GenEnergyByFuel, which is aheah of my MOD's patch. Therefore, the patch not only prevented the original function of the game, but also prevented my prepatch, so that my MOD did not work. I am powerless for this issue.
However, I can't find the source code of that FusionPower mod, so I'm not sure this is the reason.
Besides, if the artificial stars do generate empty rods but the sorter won't pick them out (if that is also called "doesn't give an empty rod back"), then may be another function named "PickFuelFrom" or "PickFrom" is blocked by his patch. I can do nothing about that either. I'm really sorry.

**Comment by James-Fire** [comment]
It worked fine for the antimatter rods. In the case of Deuteron rods, no empty rod was generated.

Here's the source code.

https://github.com/James-Fire/DSP-Mods/tree/main/Deuterium%20Stars

**Comment by jinxOAO** [comment]
That's weird, it seems that it's my problem. Give me some time.

**Comment by jinxOAO** [comment]
Funny thing is it works fine on my computer. Empty deuteron rod was generated in the artificial star. Now I'm confused. maybe some other mods cause this problem?
![image](https://user-images.githubusercontent.com/49783661/196729091-779ff3e3-c1b9-4b91-ba9f-32896d6cef09.png)

**Comment by James-Fire** [comment]
I'm not sure. I'll recheck my results and get back.
